#Site settings
name: RodK Website
url:  "http://www.rodkay.tech"  #Host name

#Navigation title and links
navigation:  
 - title: Home
   url: /home    
 - title: Portfolio
   url: /portfolio
 # - title: Blog
 #   url: /blog
   
#Build settings
markdown: kramdown  




